---
title: "Cleaning the Data"
author: "Peter Claussen"
date: "Jun 17, 2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#F0E442","#CC79A7","#000000","#734f80", "#2b5a74", "#004f39", "#787221", "#003959", "#6aaf00", "#663cd3")
```

# Introduction

From `cornVariogram.pdf`


> Harvest monitor yield data is inherently messy. \cite{simbahan.g-2004} identify six types of erroneous data, which they screen before analysis. We will try to keep as much original data as possible, and interpolate expected values for outliers.


I have some sample fields in a related project. 

<<>>=
raw.dat <- read.csv("Swest_Corn2013-Clean.csv", header = TRUE)
summary(raw.dat)
@

Our primary response will be yield, reported in dry volume. How is this distributed?

<<fig=TRUE,width=6,height=4>>=
par(mfrow=c(2,2))
hist(raw.dat$YldMassDry,main="YldMassDry")
hist(raw.dat$YldMassWet,main="YldMassWet")
hist(raw.dat$YldVolDry,main="YldVolDry")
hist(raw.dat$YldVolWet,main="YldVolWet")
par(mfrow=c(1,1))
@

We could use any of the four yield measures, they appear to be roughly equivalent. 


\section*{Cleaning the data}
Our task is to impute yield data for single passes in the field. Figure \ref{raw_plot} shows the original data colored by pass number. This gives us an idea about the order which data were collected. We note that passes were not made in an orderly progression across the field. This will complicate our analysis later if we want to determine relationships among neighboring passes.

<<fig=TRUE,width=6,height=4>>=
ggplot(raw.dat, aes(Longitude, Latitude)) + geom_point(aes(colour = PassNum),size = 1)
@

We want to discard the endrows. They generally won't be representative of the field in general, since during planting the soil is passed over more frequently. Examining \ref{raw_plot}, we can assign upper and lower bounds for analysis. We'll refer to this as the trimmed data set.

<<>>=
northBorder <- 43.23575
southBorder <- 43.22975
trimmed.dat <- subset(raw.dat,raw.dat$Latitude>=southBorder)
trimmed.dat <- subset(trimmed.dat,trimmed.dat$Latitude<=northBorder)
@

<<fig=TRUE,width=6,height=4>>=
ggplot(trimmed.dat, aes(Longitude, Latitude)) + geom_point(aes(colour = YldVolDry),size = 1)
@

\section*{Subset data set}

The \verb|kriging| function slows my system greatly, so we need to start with a subset
of the full data set to explore variagrams for this type of data. 

We'll start with the middle $1/25$ of the trimmed field. I'm labelling the subset to simplify plotting. We'll refer to this data set as the sample data set.

<<>>=
min.lat <- min(trimmed.dat$Latitude)
max.lat <- max(trimmed.dat$Latitude)
min.lon <- min(trimmed.dat$Longitude)
max.lon <- max(trimmed.dat$Longitude)
lat.rng <- max.lat-min.lat
lon.rng <- max.lon-min.lon
trimmed.dat$Sample <- trimmed.dat$Latitude>(min.lat + 2*(lat.rng/5)) & 
                   trimmed.dat$Latitude<(max.lat - 2*(lat.rng/5)) &
                   trimmed.dat$Longitude>(min.lon + 2*(lon.rng/5)) &
                   trimmed.dat$Longitude<(max.lon - 2*(lon.rng/5))
sample.dat <- subset(trimmed.dat,trimmed.dat$Sample)
@

Examine the trimmed data and sample.

<<fig=TRUE,width=6,height=4>>=
ggplot(trimmed.dat, aes(Longitude, Latitude)) + geom_point(aes(colour = Sample),size = 1)
@

<<fig=TRUE,width=6,height=4>>=
ggplot(sample.dat, aes(Longitude, Latitude)) + geom_point(aes(colour = YldVolDry),size = 2)
@

\verb|PassNum| tells us the order which the combine moves up or down the field. This is not in
longitudinal order, so we need to convert. First, we average the longitude of each pass, the
rank values to get a spatial order. We add these to the sample data set. Note that I'm creating factors for pass number and order so we can visualize these. We'll use the pass order number in Figure \ref{sample_order} to remove a single pass from the middle of the sample for interpolation.

<<>>=
sample.dat$Pass <- as.factor(sample.dat$PassNum)
pass.long <- tapply(sample.dat$Longitude,list(sample.dat$Pass),mean)
sample.dat$Order <- rank(pass.long)[sample.dat$Pass]
sample.dat$PassOrder <- as.factor(sample.dat$Order)
@


<<fig=TRUE,width=6,height=4>>=
ggplot(sample.dat, aes(Longitude, Latitude)) + geom_point(aes(colour = Pass),size = 2)
@

\begin{figure}\centering
<<fig=TRUE,width=6,height=4>>=
ggplot(sample.dat, aes(Longitude, Latitude)) + geom_point(aes(colour = PassOrder),size = 2)
@
\caption{Sample region, colored by Order (east to west)}\label{sample_order}\end{figure}

\clearpage


\subsubsection*{Estimating Pass Number}

First attempt, we realize that when moving north to south (or vice-versa), latitude will change much more rapidly than longitude. For 45 degree path, longitude and latitude will change at the same rate, so if we use this as a cutoff, we can allow for some jumps in GPS - see \ref{sample_order}.
So, we'll iterate over the data set, and increment pass when $\Delta lon > 2 \times \Delta lat$. I've found this works better identifying north-south passes than strict equality. This does overestimate the number of east-west passes, but we can remove these later.

<<>>=
raw.dat$ImpPass <- 0
impPass <- 1
i=1
raw.dat$ImpPass[i] <- impPass
raw.dat$DirLon <- NA
raw.dat$DirLat <- NA
while(i<length(raw.dat$ImpPass)) {
   delta.Lon <- raw.dat$Longitude[i+1] - raw.dat$Longitude[i]
   delta.Lat <- raw.dat$Latitude[i+1] - raw.dat$Latitude[i]
   if(delta.Lon > 0 ) {
      #moving west
      raw.dat$DirLon[i+1] <- "W"
   } else {
      raw.dat$DirLon[i+1] <- "E"
   }
   
   if(delta.Lat > 0 ) {
      #moving south
      raw.dat$DirLat[i+1] <- "S"
   } else {
      raw.dat$DirLat[i+1] <- "N"
   }
   
   delta.Lon <- abs(delta.Lon)
   delta.Lat <- abs(delta.Lat)
   
   if(delta.Lon > delta.Lat) {
      impPass = impPass+1
   }
   raw.dat$ImpPass[i+1] <- impPass
   i <- i+1
}

raw.dat$DirLon <- as.factor(raw.dat$DirLon)
raw.dat$DirLat <- as.factor(raw.dat$DirLat)
@

<<fig=TRUE,width=6,height=4>>=
ggplot(raw.dat, aes(Longitude, Latitude)) + geom_point(aes(colour = DirLat),size = 1)
@

Note that there are many incomplete passes, finished in opposite directions.

<<fig=TRUE,width=6,height=4>>=
endrowsN.dat <- subset(raw.dat,raw.dat$Latitude>northBorder)
ggplot(endrowsN.dat, aes(Longitude, Latitude)) + geom_point(aes(colour = DirLat),size = 1)
@
 At the north end, we see an offset from the southernmost endrow ...

<<fig=TRUE,width=6,height=4>>=
endrowsS.dat <- subset(raw.dat,raw.dat$Latitude<southBorder)
ggplot(endrowsS.dat, aes(Longitude, Latitude)) + geom_point(aes(colour = DirLat),size = 1)
@
... and a corresponding offset at the south end of the field

This suggests that we can reduce some error by shifting passes. This will have an effect on passes that are harvested in different directions. Points in these passes are offset relative to each other and kriging will be based on incorrect linear distances. This will affect more than just pairs of passes in opposite directions, depending on the sphere of influence detected by the variogram.

<<>>=
raw.dat$ImpPass <- as.factor(raw.dat$ImpPass)
raw.passes <- tapply(raw.dat$PassNum, list(raw.dat$PassNum),length)
raw.pasimp <- tapply(raw.dat$ImpPass, list(raw.dat$ImpPass),length)
@

We still don't compute passes as completely as we might wish. There are still passes that are shorter than the length of the field, as we might expect.

<<>>=
problem.passes <- names(raw.passes[(which(raw.passes<400 | raw.passes>550))])
problem.imp <- names(raw.pasimp[(which(raw.pasimp<400 | raw.pasimp>550))])
problem.dat <- subset(raw.dat,raw.dat$ImpPass %in% problem.imp)
problem.dat$ImpPass <- as.factor(as.numeric(problem.dat$ImpPass))
@

<<fig=TRUE,width=6,height=4>>=
ggplot(problem.dat, aes(Longitude, Latitude)) + geom_point(aes(color=DirLat),size = 2)
@

Note that most of the incomplete passes are in the north endrows, which we exclude from analysis. However, there are some incomplete passes in the main data. Note that some passes in the same geographic pass (in line with planting) appear to be harvested in different directions

If we consider an interior portion of the map, there appear to be many breaks along a line. Perhaps there is a geographical feature? Some of these gaps may be explained by a partial harvest pass, followed by a finishing pass in the opposite direction. This is an issue that may be addressed in execution.

<<fig=TRUE,width=6,height=4>>=
breaks.dat <- subset(raw.dat,raw.dat$Latitude < 43.23225)
breaks.dat <- subset(breaks.dat,breaks.dat$Latitude > 43.2310)
ggplot(breaks.dat, aes(Longitude, Latitude)) + geom_point(aes(color=DirLat),size = 2)
@

\clearpage
\subsubsection*{Computing Vertical Offset}

We can use the north endrows to estimate a mean offset, based on direction traveled. First, we need to identify the passes that are unique to the north endrows. We assume that passes in the trimmed data set are strictly north-south.

<<>>=
endrowsN.dat$Endrow <- !(endrowsN.dat$PassNum %in% trimmed.dat$PassNum)
@

Plot this to check our assumptions.

<<fig=TRUE,width=6,height=4>>=
ggplot(endrowsN.dat, aes(Longitude, Latitude)) + geom_point(aes(colour = Endrow),size = 1)
@


It appears that pass number continues across the north end of the field. However, we note the southern-most endrow pass is uniquely identified. 

We note that the sides of the field have passes that extend well into the endrow range. We can trim from the sides and remove a portion of the northern endrow. I've chosen latitude and longitude by inspection.

<<fig=TRUE,width=6,height=4>>=
endrowStrip <- subset(raw.dat,raw.dat$Latitude < 43.236)
endrowStrip <- subset(endrowStrip,endrowStrip$Latitude > 43.2358)
endrowStrip <- subset(endrowStrip,endrowStrip$Longitude < -96.897)
endrowStrip <- subset(endrowStrip,endrowStrip$Longitude > -96.900)
ggplot(endrowStrip, aes(Longitude, Latitude)) + geom_point(aes(colour = DirLat),size = 1)
@

We now have only two east-west passes. Since this data set is trimmed from north to south, we can remove these two rows based on the number of observations.

<<>>=
endrowStrip$Pass <- as.factor(endrowStrip$PassNum)
endrowStrip.count <- tapply(endrowStrip$Pass, list(endrowStrip$PassNum), length)
@

The east-west passes are the only passes with more than 100 observations, so select on that criteria.

<<>>=
ew.rows <- names(endrowStrip.count)[which(endrowStrip.count>100)]
ew.rows <- as.numeric(ew.rows)
ew.rows
@

Looks like we take out rows 17 and 20.

<<>>=
endrowStrip <- subset(endrowStrip, !(endrowStrip$PassNum %in% ew.rows))
@

<<>>=
tapply(endrowStrip$Latitude, list(endrowStrip$PassNum), max)
@

Now we classify passes by direction. We'll take a ratio to allow for endpoints. The direction of travel for endpoints may not be correctly inferred, since direction is based on distance from a previous point. 

<<>>=
endrowStrip$North <- endrowStrip$DirLat=="N"
endrowStrip$South <- endrowStrip$DirLat=="S"
Ncounts <- tapply(endrowStrip$North,list(endrowStrip$Pass),sum)
counts <- tapply(endrowStrip$South,list(endrowStrip$Pass),length)
nRatio <- Ncounts/counts

Northward <- nRatio>0.5
Northward <- as.factor(Northward)
@

Having classified passes by direction, we create subsets for later use.

<<>>=
northPasses <- as.numeric(names(Northward)[Northward==TRUE])
southPasses <- as.numeric(names(Northward)[Northward==FALSE])

southPasses <- subset(southPasses,!is.na(southPasses))
northPasses <- subset(northPasses,!is.na(northPasses))
@

Now we compute for each pass the northern most point, and take the average for north and south passes.

<<>>=
maxPoint <- tapply(endrowStrip$Latitude,list(endrowStrip$Pass),max) 
NSpoints <- tapply(maxPoint,list(Northward),mean)
@

Now we can compute an offset; we assume the midpoint between pass maximums for north and south passes.

<<>>=
offset <- abs((NSpoints[2]-NSpoints[1]))/2
endrowStrip$LatOff <- endrowStrip$Latitude + offset
mask <- endrowStrip$Pass %in% northPasses
endrowStrip$LatOff[mask] <- endrowStrip$Latitude[mask] - offset
@

So, what does the offset look like?

<<fig=TRUE,width=6,height=4>>=
ggplot(endrowStrip, aes(Longitude, LatOff)) + geom_point(aes(colour = DirLat),size = 1)
@

This doesn't adjust all the passes in the endrow set but we might improve this when we use estimated pass numbers in the larger data set.

\subsection*{Estimating passes, trimmed data set}

Now we apply the shift to a slightly larger data set than the trimmed set. After we make adjustments, we'll trim to match our previous data.


<<>>=
northExtra <- northBorder+offset
southExtra <- southBorder-offset
reduced.dat <- subset(raw.dat,raw.dat$Latitude>=southExtra)
reduced.dat <- subset(reduced.dat,reduced.dat$Latitude<=northExtra)
@

Repeat pass estimation, without the endrows. This may improve our ability to detect passes. I've also included a check for a time gap. Since we've trimmed ends, each geographical pass represents a gap in sample ids.

<<>>=
reduced.dat$ImpPass <- 0
impPass <- 1
i <- 1
reduced.dat$ImpPass[i] <- impPass
reduced.dat$DirLon <- NA
reduced.dat$DirLat <- NA
reduced.dat$DirLon[i] <- "W"
reduced.dat$DirLat[i] <- "N"
current.count = 1
while(i < length(reduced.dat$ImpPass)) {
   
   delta.Lon <- reduced.dat$Longitude[i+1]-reduced.dat$Longitude[i]
   delta.Lat <- reduced.dat$Latitude[i+1]-reduced.dat$Latitude[i]
   if(delta.Lon > 0 ) {
      #moving west
      reduced.dat$DirLon[i+1] <- "W"
   } else {
      reduced.dat$DirLon[i+1] <- "E"
   }
   
   if(delta.Lat > 0 ) {
      #moving south
      reduced.dat$DirLat[i+1] <- "S"
   } else {
      reduced.dat$DirLat[i+1] <- "N"
   }
   
   #is there a time gap
   #time.gap <- reduced.dat$ID[i+1]-reduced.dat$ID[i]
   #OID works better than ID, 
   time.gap <- reduced.dat$OID[i+1]-reduced.dat$OID[i]

   if(time.gap > 1) {
      impPass = impPass+1
   }
   
   reduced.dat$ImpPass[i+1] <- impPass
   i <- i+1
   current.count <- current.count+1
}

reduced.dat$DirLon <- as.factor(reduced.dat$DirLon)
reduced.dat$DirLat <- as.factor(reduced.dat$DirLat)
reduced.dat$ImpPass <- as.factor(reduced.dat$ImpPass)
tapply(reduced.dat$ImpPass,list(reduced.dat$ImpPass),length)
@

<<>>=
reduced.dat$North <- reduced.dat$DirLat=="N"
reduced.dat$South <- reduced.dat$DirLat=="S"
Ncounts <- tapply(reduced.dat$North,list(reduced.dat$ImpPass),sum,na.rm=TRUE)
Ncounts[is.na(Ncounts)] <- 0
counts <- tapply(reduced.dat$North,list(reduced.dat$ImpPass),length)
nRatio <- Ncounts/counts

Northward <- nRatio>0.5
Northward <- as.factor(Northward)

northPasses <- as.numeric(names(Northward)[Northward==TRUE])
southPasses <- as.numeric(names(Northward)[Northward==FALSE])

southPasses <- subset(southPasses,!is.na(southPasses))
northPasses <- subset(northPasses,!is.na(northPasses))

reduced.dat$LatOff <- reduced.dat$Latitude + offset

mask <- reduced.dat$ImpPass %in% northPasses
reduced.dat$LatOff[mask] <- reduced.dat$Latitude[mask] - offset
@

<<fig=TRUE,width=6,height=4>>=
ggplot(reduced.dat, aes(Longitude, LatOff)) + geom_point(aes(colour = DirLat),size = 1)
@

This appears to remove some of the gaps in the center of the field, so we'll examine the middle in greater detail

<<fig=TRUE,width=6,height=4>>=
red.breaks.dat <- subset(reduced.dat,reduced.dat$LatOff < 43.23225)
red.breaks.dat <- subset(red.breaks.dat,red.breaks.dat$LatOff > 43.2310)
ggplot(red.breaks.dat, aes(Longitude, LatOff)) + geom_point(aes(color=DirLat),size = 2)
@

This reduces most of the mid-field gaps, but we are left with shortened passes. If we try to adjust horizontal displacements, we combine some passes.

<<fig=TRUE,width=6,height=4>>=
ggplot(reduced.dat, aes(LatOff,Longitude)) + 
   geom_point(aes(colour = ImpPass),size = 1) + 
   geom_smooth(method = "loess",aes(group = ImpPass),color="black")
@

\clearpage
We note that short passes may result from a change in direction, so I've added a check for change in direction, and a check for the length of the current pass. When we guess direction, the end point in a pass is not always correct.

<<>>=
reduced.dat$ImpPass <- 0
impPass <- 1
i <- 1
reduced.dat$ImpPass[i] <- impPass
reduced.dat$DirLon <- NA
reduced.dat$DirLat <- NA
reduced.dat$DirLon[i] <- "W"
reduced.dat$DirLat[i] <- "N"
current.count = 1
while(i < length(reduced.dat$ImpPass)) {
   
   delta.Lon <- reduced.dat$Longitude[i+1]-reduced.dat$Longitude[i]
   delta.Lat <- reduced.dat$Latitude[i+1]-reduced.dat$Latitude[i]
   if(delta.Lon > 0 ) {
      #moving west
      reduced.dat$DirLon[i+1] <- "W"
   } else {
      reduced.dat$DirLon[i+1] <- "E"
   }
   
   if(delta.Lat > 0 ) {
      #moving south
      reduced.dat$DirLat[i+1] <- "S"
   } else {
      reduced.dat$DirLat[i+1] <- "N"
   }
   
   #is there a time gap
   #time.gap <- reduced.dat$ID[i+1]-reduced.dat$ID[i]
   #OID works better than ID, 
   time.gap <- reduced.dat$OID[i+1]-reduced.dat$OID[i]
   
   delta.Lon <- abs(delta.Lon)
   delta.Lat <- abs(delta.Lat)
   
   if(time.gap > 1) {
      if(current.count>2) {
         impPass = impPass+1
         current.count <- 1
      }
   } else if(reduced.dat$DirLat[i+1] != reduced.dat$DirLat[i]) {
      if(current.count>2) {
         impPass = impPass+1
         current.count <- 1
      }
   }
   
   reduced.dat$ImpPass[i+1] <- impPass
   i <- i+1
   current.count <- current.count+1
}

reduced.dat$DirLon <- as.factor(reduced.dat$DirLon)
reduced.dat$DirLat <- as.factor(reduced.dat$DirLat)
reduced.dat$ImpPass <- as.factor(reduced.dat$ImpPass)
tapply(reduced.dat$ImpPass,list(reduced.dat$ImpPass),length)
@

This looks good; all passes have a reasonable number of points. We'll further process as before.

<<>>=
reduced.dat$North <- reduced.dat$DirLat=="N"
reduced.dat$South <- reduced.dat$DirLat=="S"
Ncounts <- tapply(reduced.dat$North,list(reduced.dat$ImpPass),sum,na.rm=TRUE)
Ncounts[is.na(Ncounts)] <- 0
counts <- tapply(reduced.dat$North,list(reduced.dat$ImpPass),length)
nRatio <- Ncounts/counts

Northward <- nRatio>0.5
Northward <- as.factor(Northward)

northPasses <- as.numeric(names(Northward)[Northward==TRUE])
southPasses <- as.numeric(names(Northward)[Northward==FALSE])

northPasses
southPasses

southPasses <- subset(southPasses,!is.na(southPasses))
northPasses <- subset(northPasses,!is.na(northPasses))

reduced.dat$LatOff <- reduced.dat$Latitude + offset

mask <- reduced.dat$ImpPass %in% northPasses
reduced.dat$LatOff[mask] <- reduced.dat$Latitude[mask] - offset
@

Now we trim the reduced data set to match our previously trimmed set.

<<>>=
adj.trimmed.dat <- subset(reduced.dat,reduced.dat$LatOff>=southBorder)
adj.trimmed.dat <- subset(adj.trimmed.dat,adj.trimmed.dat$LatOff<=northBorder)
@

We want to visualize passes. We also want to remove the extra imputed pass numbers.

<<>>=
adj.trimmed.dat$ImpPassNum <- as.numeric(adj.trimmed.dat$ImpPass)
adj.trimmed.dat$ImpPass <- as.factor(adj.trimmed.dat$ImpPassNum)
counts <- tapply(adj.trimmed.dat$ImpPass,list(adj.trimmed.dat$ImpPass),length)
longest_pass <- as.numeric(names(counts)[which(counts==max(counts))])
@


\begin{figure}\centering
<<fig=TRUE,width=6,height=4>>=
ggplot(subset(adj.trimmed.dat,adj.trimmed.dat$ImpPassNum==longest_pass), aes(Longitude, LatOff)) + geom_point(size = 2)
@
\caption{Longest pass in trimmed data}\label{long_trimmed_plot}
\end{figure}

Figure \ref{long_trimmed_plot} shows the longest, with regard to the number of points, in the adjusted and trimmed data. Note that since there is only one pass in the, horizontal displacement is greatly exaggerated. Now that we've estimated passes, we can try to estimate longitude for the full data set.

<<fig=TRUE,width=6,height=4>>=
ggplot(adj.trimmed.dat, aes(LatOff,Longitude)) + 
   geom_point(aes(colour = ImpPass),size = 1) + 
   geom_smooth(method = "loess",aes(group = ImpPass),color="black")
@

We see that we don't combine short passes.

<<>>=
adj.trimmed.dat$LonAdj <- adj.trimmed.dat$Longitude
adj.trimmed.dat$LonIsAdj <- FALSE
for (pass in adj.trimmed.dat$ImpPass) {
   pass.dat <- subset(adj.trimmed.dat,adj.trimmed.dat$ImpPass==pass)
   if(length(pass.dat$LonAdj)<550 && length(pass.dat$LonAdj)>100) {
      pass.loess <- loess(Longitude ~ LatOff,data=pass.dat)
      adj.trimmed.dat$LonAdj[adj.trimmed.dat$ImpPass==pass] <- pass.loess$fitted
      adj.trimmed.dat$LonIsAdj[adj.trimmed.dat$ImpPass==pass] <- TRUE
   }
}
@

<<fig=TRUE,width=6,height=4>>=
ggplot(adj.trimmed.dat, aes(LatOff,LonAdj)) + 
   geom_point(aes(colour = ImpPass),size = 2) + 
   geom_smooth(method = "loess",aes(group = ImpPass),color="black")
@


