---
title: "Field G"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
#theme_set(theme_dag())
#since we have k-fold cross validation

set.seed(1000)
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)

library(mgcv)
library(splines)

#library(ape)

yellow <- "#F0E442"
blue <- "#0072B2"
vermillion <- "#D55E00"
  
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#F0E442","#CC79A7","#000000","#734f80", "#2b5a74", "#004f39", "#787221", "#003959", "#6aaf00", "#663cd3")


source('./R/remove.harvest.outliers.fn.R')
source('./R/spatial.model.selection.R')
source('./R/select.best.variogram.R')
source('./R/spatial.selection.plots.R')
source('./R/read.yield.data.R')
source('./R/combined.map.R')
```


Elbow plot/Elbow method


## Load Data


```{r,eval=TRUE,echo=FALSE}
field = 'G'
root = '../ManagementZoneML/data/'

#2014 is incomplete
#Years <- c(2013,2014,2015,2016,2017,2018,2020,2021)
#Crops <- c('Corn','Soybeans','Corn','Soybeans','Corn','Soybeans','Corn','Soybeans')

Years <- c(2013,2015,2016,2017,2018,2020,2021)
Crops <- c('Corn','Corn','Soybeans','Corn','Soybeans','Corn','Soybeans')

harvests <-vector(mode='list',length=length(Years))
for(i in 1:length(Years)) {
  harvests[[i]] <- read.yield.data(root,field,Years[i],Crops[i])
}

min.corner <- Inf
for(i in 1:length(Years)) {
  if( min(harvests[[i]]$Longitude) < min.corner) {
    min.corner <- min(harvests[[i]]$Longitude)
  }
}

for(i in 1:length(Years)) {
  harvests[[i]]$Longitude <- harvests[[i]]$Longitude-min.corner
}

```


```{r,fig.width=8,fig.height=4.5,echo=FALSE}
Maps6 <- combined.map(harvests)
ggplot(Maps6, aes(Longitude,Latitude)) + 
geom_point(aes(colour = Quantile),size=.5) + 
scale_colour_gradient2(low=vermillion, mid=yellow, high=blue, midpoint = 0.5) +
labs(colour = "Relative Yield Rank", x="Easting", y="Northing", title = "Multiple Years") + facet_wrap(~ Map)
```

```{r}
powers <- 2^(1:6)
results <- expand.grid(powers,Years)
names(results) <- c("Power","Year")
results$WSS <- NA
results$BSS <- NA
results$Cells <- NA

results$ResVar <- NA
results$CellVar <- NA

for (p in powers) {
  for(y in 1:length(Years)) {
    current <- harvests[[y]]
    LatRange <- (max(current$Latitude) - min(current$Latitude))/p
    current$Row <- ceiling((current$Latitude- min(current$Latitude))/LatRange)
    
    LongRange <- (max(current$Longitude) - min(current$Longitude))/p
    current$Col <- ceiling((current$Longitude-min(current$Longitude))/LongRange)

    current$Cell <- current$Row*1000 + current$Col
    Cells <- unique(current$Cell)
    #currentCells <- aggregate(Yield~Cell, data=current, FUN=mean)
    current$Cell <- as.factor(current$Cell)
    mask <- results$Power==p & results$Year==Years[y]
    results$Cells[mask] <- length(Cells)
    current.lm <- lm(Yield~Cell,data=current)
    aov.tbl <- summary(aov(current.lm))
    results$BSS[mask] <- aov.tbl[[1]]['Cell','Sum Sq']
    results$WSS[mask] <- aov.tbl[[1]]['Residuals','Sum Sq']
    #current.lme <- lme(Yield~1, random =  1| Cell,data=currentCells)
    #vc <- VarCorr(current.lme)
  }
  
}
results$Cells <- as.factor(results$Cells)
```


```{r,echo=FALSE,fig.width=8,fig.height=4}
ggplot(results, aes(WSS,BSS)) + 
    geom_point(aes(colour = Cells),size=2) #+ 
  #  geom_smooth(aes(group = Year,color=Year), se=FALSE) +
   # scale_colour_manual(values=c(cbPalette)) #+ facet_wrap(~Method) +
    #labs(title = "Nugget Selection, Residual Variograms")
```







```{r}
grid <- 5*2:20
results <- expand.grid(grid,Years)
names(results) <- c("Grid","Year")
results$WSS <- NA
results$BSS <- NA
results$Cells <- NA

results$ResVar <- NA
results$CellVar <- NA

for (g in grid) {
  for(y in 1:length(Years)) {
    current <- harvests[[y]]
    current$Row <- ceiling(current$Latitude/g)
    current$Col <- ceiling(current$Longitude/g)
    current$Cell <- current$Row*1000 + current$Col
    Cells <- unique(current$Cell)
    #currentCells <- aggregate(Yield~Cell, data=current, FUN=mean)
    current$Cell <- as.factor(current$Cell)
    mask <- results$Grid==g & results$Year==Years[y]
    results$Cells[mask] <- length(Cells)
    current.lm <- lm(Yield~Cell,data=current)
    aov.tbl <- summary(aov(current.lm))
    results$BSS[mask] <- aov.tbl[[1]]['Cell','Sum Sq']
    results$WSS[mask] <- aov.tbl[[1]]['Residuals','Sum Sq']
    current.lme <- lme(Yield~1, random =  ~1| Cell,data=current)
    vc <- VarCorr(current.lme)
    results$ResVar[mask] <- as.numeric(vc[2,1])
    results$CellVar[mask] <- as.numeric(vc[1,1])
  }
  
}
results$Cells <- as.factor(results$Cells)
results$Year <- as.factor(results$Year)
```


```{r,echo=FALSE,fig.width=8,fig.height=4}
ggplot(results, aes(Cells,BSS)) + 
    geom_point(aes(colour = Year),size=2) #+ 
  #  geom_smooth(aes(group = Year,color=Year), se=FALSE) +
   # scale_colour_manual(values=c(cbPalette)) #+ facet_wrap(~Method) +
    #labs(title = "Nugget Selection, Residual Variograms")
```



```{r,echo=FALSE,fig.width=8,fig.height=4}
ggplot(results, aes(Cells,CellVar)) + 
    geom_point(aes(colour = Year),size=2) #+ 
  #  geom_smooth(aes(group = Year,color=Year), se=FALSE) +
   # scale_colour_manual(values=c(cbPalette)) #+ facet_wrap(~Method) +
    #labs(title = "Nugget Selection, Residual Variograms")
```
