---
title: "Overview"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
#theme_set(theme_dag())
#since we have k-fold cross validation

set.seed(1000)
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)

library(mgcv)
library(splines)
library(gstat)
library(ape)

grey <- "#999999"
orange <- "#E69F00"
skyblue <- "#56B4E9"
bluishgreen <- "#009E73"
yellow <- "#F0E442"
blue <- "#0072B2"
vermillion <- "#D55E00"
  
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#F0E442","#CC79A7","#000000","#734f80", "#2b5a74", "#004f39", "#787221", "#003959", "#6aaf00", "#663cd3")


source('./R/remove.harvest.outliers.fn.R')
source('./R/spatial.model.selection.R')
source('./R/select.best.variogram.R')
```



## Load Data


```{r,eval=TRUE}
harvest.2016.dat <- read.csv(file='../ManagementZoneML/data/I 2016 Wheat Harvest.csv')
harvest.2017.dat <- read.csv(file='../ManagementZoneML/data/I 2017 Corn Harvest.csv')
harvest.2018.dat <- read.csv(file='../ManagementZoneML/data/I 2018 Soybean Harvest.csv')
harvest.2019.dat <- read.csv(file='../ManagementZoneML/data/I 2019 Corn Harvest.csv')

harvest.2019.dat <- remove.harvest.outliers.fn(harvest.2019.dat)
harvest.2018.dat <- remove.harvest.outliers.fn(harvest.2018.dat)
harvest.2016.dat <- remove.harvest.outliers.fn(harvest.2016.dat)
harvest.2017.dat <- remove.harvest.outliers.fn(harvest.2017.dat)
```


```{r,fig.width=8,fig.height=4.5,echo=FALSE}
Maps6 <- data.frame(Longitude=c(harvest.2019.dat$Longitude,
                                harvest.2018.dat$Longitude,
                                harvest.2017.dat$Longitude,
                                harvest.2016.dat$Longitude),
                   Latitude=c(harvest.2019.dat$Latitude,
                              harvest.2018.dat$Latitude,
                              harvest.2017.dat$Latitude,
                              harvest.2016.dat$Latitude),
                   Value=c(rank(harvest.2019.dat$Yield)/max(rank(harvest.2019.dat$Yield)),
                           rank(harvest.2018.dat$Yield)/max(rank(harvest.2018.dat$Yield)),
                           rank(harvest.2017.dat$Yield)/max(rank(harvest.2017.dat$Yield)),
                           rank(harvest.2016.dat$Yield)/max(rank(harvest.2016.dat$Yield))),
                   Map=c(rep(2019,length(harvest.2019.dat$Yield)),
                         rep(2018,length(harvest.2018.dat$Yield)),
                         rep(2017,length(harvest.2017.dat$Yield)),
                         rep(2016,length(harvest.2016.dat$Yield))))
ggplot(Maps6, aes(Longitude,Latitude)) + 
geom_point(aes(colour = Value),size=.5) + 
scale_colour_gradient2(low=vermillion, mid=yellow, high=blue, midpoint = 0.5) +
labs(colour = "Relative Rank", x="Easting", y="Northing", title = "Multiple Years") + facet_wrap(~ Map)
```


---
title: "Field I"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
#theme_set(theme_dag())
#since we have k-fold cross validation

set.seed(1000)
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)

library(mgcv)
library(splines)

#library(ape)

yellow <- "#F0E442"
blue <- "#0072B2"
vermillion <- "#D55E00"
  
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#F0E442","#CC79A7","#000000","#734f80", "#2b5a74", "#004f39", "#787221", "#003959", "#6aaf00", "#663cd3")


source('./R/remove.harvest.outliers.fn.R')
source('./R/spatial.model.selection.R')
source('./R/select.best.variogram.R')
source('./R/spatial.selection.plots.R')
source('./R/read.yield.data.R')
source('./R/combined.map.R')
```


## Load Data


```{r,eval=TRUE,echo=FALSE}
field = 'I'
root = '../ManagementZoneML/data/'

Years <- c(2013,2014,2015,2016,2017,2018,2020)
Crops <- c('Corn','Soybeans','Corn','Soybeans','Corn','Soybeans','Corn')
harvests <-vector(mode='list',length=length(Years))
for(i in 1:length(Years)) {
  harvests[[i]] <- read.yield.data(root,field,Years[i],Crops[i])
}
```


```{r,fig.width=8,fig.height=4.5,echo=FALSE}
Maps6 <- combined.map(harvests)
ggplot(Maps6, aes(Longitude,Latitude)) + 
geom_point(aes(colour = Quantile),size=.5) + 
scale_colour_gradient2(low=vermillion, mid=yellow, high=blue, midpoint = 0.5) +
labs(colour = "Relative Yield Rank", x="Easting", y="Northing", title = "Multiple Years") + facet_wrap(~ Map)
```


# Model Selection

## ns

```{r}
methods=c('ns','bs','gam','te','tp','lm')
# methods <- methods[1:2]
# re c(2,9),

ranges = matrix(c(c(3,35),
                  c(3,35),
                  c(4,300),
                  c(3,24),
                  c(3,24),
                  c(2,12)),ncol=2,byrow=TRUE)
models=8

Methods = vector(mode='list',length=length(methods))
```

## Iteration over Croplands and Methods

```{r,echo=FALSE,fig.width=6,fig.height=4}
for(j in 1:length(methods)) {
  prof.name = paste('profile',methods[j],sep='')
  Rprof(prof.name)
  Models <- vector(mode='list',length=length(Years))
  Plots <- vector(mode='list',length=length(Years))

  for(i in 1:length(Years)) {
    Models[[i]] <- spatial.model.selection(harvests[[i]],
                                           range=ranges[j,],
                                           method=methods[j],
                                           models=models)
    Plots[[i]] <- spatial.selection.plots(Models[[i]])
    #print(summary(lm(Gamma ~ 0 + K + K:Distance,data=Models[[i]]$ResidualsData)))
    print(Plots[[i]])
  }
  
  SelectionG <- NULL
  BestBICG <- NULL
  BestSlopeG <- NULL
  BestNuggetG <- NULL

  for(i in 1:length(Years)) {
    tmp <- Models[[i]]$Selection
    tmp$Year <- Years[i]
    SelectionG <- rbind(SelectionG,tmp)
  
    tmp <- select.best.variogram(Models[[i]])
    tmp$Year <- Years[i]
    BestBICG <- rbind(BestBICG,tmp)

    tmp <- select.best.variogram(Models[[i]],criteria='slope')
    tmp$Year <- Years[i]
    BestSlopeG <- rbind(BestSlopeG,tmp)
    
    tmp <- select.best.variogram(Models[[i]],criteria='nugget')
    tmp$Year <- Years[i]
    BestNuggetG <- rbind(BestNuggetG,tmp)
  }
  Rprof(NULL)
  
  Methods[[j]] <- list(Models=Models,
                       Plots=Plots,
                       Selection=SelectionG,
                       BestBIC=BestBICG,
                       BestSlope=BestSlopeG,
                       BestNugget=BestNuggetG)
}

```

\pagebreak

# Model Selection Comparisons

```{r}
SummaryBIC <- NULL
SummarySlope <- NULL
SummaryNugget <- NULL
```

```{r,echo=FALSE,fig.width=6,fig.height=3}
for(i in 1:length(methods)) {
  BestBIC <- Methods[[i]]$BestBIC
  BestBIC$Year <- factor(BestBIC$Year)
  bicplot <- ggplot(BestBIC, aes(Distance,Gamma)) + 
    geom_point(aes(colour = Year),size=2) + 
    geom_smooth(aes(group = Year,color=Year), se=FALSE) +
    scale_colour_manual(values=c(cbPalette)) + facet_wrap(~Source) +
    labs(title = paste(methods[i],"Selected by BIC"))
  
  print(bicplot) 
  
  BestSlope <- Methods[[i]]$BestSlope
  BestSlope$Year <- factor(BestSlope$Year)
  slopeplot <- ggplot(BestSlope, aes(Distance,Gamma)) + 
    geom_point(aes(colour = Year),size=2) + 
    geom_smooth(aes(group = Year,color=Year), se=FALSE) +
    scale_colour_manual(values=c(cbPalette)) + facet_wrap(~Source) +
    labs(title = paste(methods[i],"Selected by Slope"))

  print(slopeplot)
  
  BestNugget <- Methods[[i]]$BestNugget
  BestNugget$Year <- factor(BestNugget$Year)
  nuggetplot <- ggplot(BestNugget, aes(Distance,Gamma)) + 
    geom_point(aes(colour = Year),size=2) + 
    geom_smooth(aes(group = Year,color=Year), se=FALSE) +
    scale_colour_manual(values=c(cbPalette)) + facet_wrap(~Source) +
    labs(title = paste(methods[i],"Selected by Nugget"))

  print(nuggetplot)
  
  BestBIC$Method <- methods[i]
  BestSlope$Method <- methods[i]
  BestNugget$Method <- methods[i]
  
  SummaryBIC <- rbind(SummaryBIC,BestBIC)
  SummarySlope <- rbind(SummarySlope,BestSlope)
  SummaryNugget <- rbind(SummaryNugget,BestNugget)
}
```

\pagebreak

# Model Selection Averages

## Average Residuals SemiCorrelations
```{r}
ResidualsTable <- aggregate(Gamma ~ Method,data=SummaryBIC[SummaryBIC$Source=='Residuals',], mean)
names(ResidualsTable)[2] <- 'BIC'
ResidualsTable$Slope <- aggregate(Gamma ~ Method, data=SummarySlope[SummarySlope$Source=='Residuals',], mean)[,2]
ResidualsTable$Nugget <- aggregate(Gamma ~ Method, data=SummaryNugget[SummaryNugget$Source=='Residuals',], mean)[,2]
ResidualsTable
```

## Average Model SemiCorrelations

```{r}
ModelTable <- aggregate(Gamma ~ Method,data=SummaryBIC[SummaryBIC$Source=='Model',], mean)
names(ModelTable)[2] <- 'BIC'
ModelTable$Slope <- aggregate(Gamma ~ Method, data=SummarySlope[SummarySlope$Source=='Model',], mean)[,2]
ModelTable$Nugget <- aggregate(Gamma ~ Method, data=SummaryNugget[SummaryNugget$Source=='Model',], mean)[,2]
ModelTable
```

\pagebreak

# Distance Plots

```{r,echo=FALSE}
combined.distance <- function(maps) {
  
  Distance <- maps[[1]]$DISTANCE
  Sample <- 1:length(Distance)
  Year=rep(attr(maps[[1]],'Year'),length(Distance))
  
  for(i in 2:length(maps)) {
    Distance <- c(Distance,maps[[i]]$DISTANCE)
    Sample <- c(Sample,1:length(maps[[i]]$DISTANCE))
    Year=c(Year,rep(attr(maps[[i]],'Year'),length(maps[[i]]$DISTANCE)))
  }
  
  return(data.frame(Distance=Distance,
                    Sample=Sample,
                    Year=Year))
}
Distance.dat <- combined.distance(harvests)
```

```{r,echo=FALSE,fig.width=6,fig.height=3}
Distance.dat$Year <- as.factor(Distance.dat$Year)
ggplot(Distance.dat, aes(Sample,Distance)) + 
geom_point(aes(colour = Year),size=.2) + 
 scale_colour_manual(values=c(cbPalette))
aggregate(Distance ~ Year,Distance.dat,FUN=sd)
```

```{r}
for(j in 1:length(methods)) {
  prof.name = paste('profile',methods[j],sep='')
  print(paste("Profile for",methods[j]))
  print(head(summaryRprof(prof.name)$sampling.time))
  print(head(summaryRprof(prof.name)$by.self))
}
```

```{r}
save(Methods,file='ModelsI.Rda')
```