---
title: "Overview"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
#theme_set(theme_dag())
#since we have k-fold cross validation

set.seed(1000)
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
#library(ggformula)
#library(GGally)
#library(ggdag)
library(mgcv)
#library(bnlearn)
library(splines)
library(gstat)
library(ape)

  grey <- "#999999"
  orange <- "#E69F00"
  skyblue <- "#56B4E9"
  bluishgreen <- "#009E73"
  yellow <- "#F0E442"
  blue <- "#0072B2"
  vermillion <- "#D55E00"
  
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#F0E442","#CC79A7","#000000","#734f80", "#2b5a74", "#004f39", "#787221", "#003959", "#6aaf00", "#663cd3")

source('./R/remove.harvest.outliers.fn.R')
source('./R/spatial.model.selection.R')
source('./R/select.best.variogram.R')
```



## Load Data

```{r,eval=TRUE}
harvest.2013.dat <- read.csv(file='../ManagementZoneML/data/E 2013 Soybean Harvest.csv')
harvest.2014.dat <- read.csv(file='../ManagementZoneML/data/E 2014 Corn Harvest.csv')
harvest.2015.dat <- read.csv(file='../ManagementZoneML/data/E 2015 Soybean Harvest.csv')
harvest.2016.dat <- read.csv(file='../ManagementZoneML/data/E 2016 Corn Harvest.csv')
harvest.2017.dat <- read.csv(file='../ManagementZoneML/data/E 2017 Soybean Harvest.csv')
harvest.2018.dat <- read.csv(file='../ManagementZoneML/data/E 2018 Corn Harvest.csv')
harvest.2019.dat <- read.csv(file='../ManagementZoneML/data/E 2019 Soybean Harvest.csv')
harvest.2020.dat <- read.csv(file='../ManagementZoneML/data/E 2020 Corn Harvest.csv')
harvest.2021.dat <- read.csv(file='../ManagementZoneML/data/E 2021 Soybean Harvest.csv')
```



# bs Selection


## 2019

```{r}
#m='ns'
#range=c(3,35)
m='bs'
range=c(3,35)
#m='gam'
#range=c(4,400)
#par(mfrow=c(2,2))
#Models.2019 <- spatial.model.selection(harvest.2019.dat)
Models.2019 <- spatial.model.selection(harvest.2019.dat,range=range,method=m)
```

```{r}
ggplot(Models.2019$Selection, aes(K,Score)) + 
geom_point(aes(colour = Criteria),size=2) + 
  geom_line(aes(colour = Criteria),size=1) + 
 scale_colour_manual(values=cbPalette) + facet_wrap(~Criteria,nrow=3,scales="free_y")
```

```{r}
Models.2019$VariogramData$K <- factor(Models.2019$VariogramData$K )
ggplot(Models.2019$VariogramData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  #geom_line(aes(colour = K),size=1) + 
   geom_smooth(aes(group = K,color=K),
           #   method="nls", 
          #    formula=y~exp(-x/tau), # this is an nls argument,
          #   method.args = list(start=c(tau=10000)),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
Models.2019$ResidualsData$K <- factor(Models.2019$ResidualsData$K )
ggplot(Models.2019$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),
 #geom_smooth(method="nls", 
#              formula=y~1+exp(-x/tau), # this is an nls argument,
#             method.args = list(start=c(tau=.01)),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
ggplot(Models.2019$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),method='lm',
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
summary(lm(Gamma ~ 0 + K + K:Distance,data=Models.2019$ResidualsData))
```


## 2018

```{r}
#par(mfrow=c(2,2))
Models.2018 <- spatial.model.selection(harvest.2018.dat,range=range,method=m)
```

```{r}
ggplot(Models.2018$Selection, aes(K,Score)) + 
geom_point(aes(colour = Criteria),size=2) + 
  geom_line(aes(colour = Criteria),size=1) + 
 scale_colour_manual(values=cbPalette) + facet_wrap(~Criteria,nrow=3,scales="free_y")
```

```{r}
Models.2018$VariogramData$K <- factor(Models.2018$VariogramData$K )
ggplot(Models.2018$VariogramData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
   geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
Models.2018$ResidualsData$K <- factor(Models.2018$ResidualsData$K )
ggplot(Models.2018$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```



```{r}
ggplot(Models.2018$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),method='lm',
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
summary(lm(Gamma ~ 0 + K + K:Distance,data=Models.2018$ResidualsData))
```

## 2017

```{r}
#par(mfrow=c(2,2))
Models.2017 <- spatial.model.selection(harvest.2017.dat,range=range,method=m)
```

```{r}
ggplot(Models.2017$Selection, aes(K,Score)) + 
geom_point(aes(colour = Criteria),size=2) + 
  geom_line(aes(colour = Criteria),size=1) + 
 scale_colour_manual(values=cbPalette) + facet_wrap(~Criteria,nrow=3,scales="free_y")
```

```{r}
Models.2017$VariogramData$K <- factor(Models.2017$VariogramData$K )
ggplot(Models.2017$VariogramData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
   geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
Models.2017$ResidualsData$K <- factor(Models.2017$ResidualsData$K )
ggplot(Models.2017$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```


```{r}
ggplot(Models.2017$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),method='lm',
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
summary(lm(Gamma ~ 0 + K + K:Distance,data=Models.2017$ResidualsData))
```


## 2016

```{r}
#par(mfrow=c(2,2))
Models.2016 <- spatial.model.selection(harvest.2016.dat,range=range,method=m)
```

```{r}
ggplot(Models.2016$Selection, aes(K,Score)) + 
geom_point(aes(colour = Criteria),size=2) + 
  geom_line(aes(colour = Criteria),size=1) + 
 scale_colour_manual(values=cbPalette) + facet_wrap(~Criteria,nrow=3,scales="free_y")
```

```{r}
Models.2016$VariogramData$K <- factor(Models.2016$VariogramData$K )
ggplot(Models.2016$VariogramData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
   geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
Models.2016$ResidualsData$K <- factor(Models.2016$ResidualsData$K )
ggplot(Models.2016$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
ggplot(Models.2016$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),method='lm',
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
summary(lm(Gamma ~ 0 + K + K:Distance,data=Models.2016$ResidualsData))
```

## 2015

```{r}
#par(mfrow=c(2,2))
Models.2015 <- spatial.model.selection(harvest.2015.dat,range=range,method=m)
```

```{r}
ggplot(Models.2015$Selection, aes(K,Score)) + 
geom_point(aes(colour = Criteria),size=2) + 
  geom_line(aes(colour = Criteria),size=1) + 
 scale_colour_manual(values=cbPalette) + facet_wrap(~Criteria,nrow=3,scales="free_y")
```

```{r}
Models.2015$VariogramData$K <- factor(Models.2015$VariogramData$K )
ggplot(Models.2015$VariogramData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
   geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
Models.2015$ResidualsData$K <- factor(Models.2015$ResidualsData$K )
ggplot(Models.2015$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```


```{r}
ggplot(Models.2015$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),method='lm',
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
summary(lm(Gamma ~ 0 + K + K:Distance,data=Models.2015$ResidualsData))
```

## 2014

```{r}
#par(mfrow=c(2,2))
Models.2014 <- spatial.model.selection(harvest.2014.dat,range=range,method=m)
```

```{r}
ggplot(Models.2014$Selection, aes(K,Score)) + 
geom_point(aes(colour = Criteria),size=2) + 
  geom_line(aes(colour = Criteria),size=1) + 
 scale_colour_manual(values=cbPalette) + facet_wrap(~Criteria,nrow=3,scales="free_y")
```

```{r}
Models.2014$VariogramData$K <- factor(Models.2014$VariogramData$K )
ggplot(Models.2014$VariogramData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
   geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
Models.2014$ResidualsData$K <- factor(Models.2014$ResidualsData$K )
ggplot(Models.2014$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
ggplot(Models.2014$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),method='lm',
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
summary(lm(Gamma ~ 0 + K + K:Distance,data=Models.2014$ResidualsData))
```

## 2013

```{r}
#par(mfrow=c(2,2))
Models.2013 <- spatial.model.selection(harvest.2013.dat,range=range,method=m)
```

```{r}
ggplot(Models.2013$Selection, aes(K,Score)) + 
geom_point(aes(colour = Criteria),size=2) + 
  geom_line(aes(colour = Criteria),size=1) + 
 scale_colour_manual(values=cbPalette) + facet_wrap(~Criteria,nrow=3,scales="free_y")
```

```{r}
Models.2013$VariogramData$K <- factor(Models.2013$VariogramData$K )
ggplot(Models.2013$VariogramData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
   geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
Models.2013$ResidualsData$K <- factor(Models.2013$ResidualsData$K )
ggplot(Models.2013$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
ggplot(Models.2013$ResidualsData, aes(Distance,Gamma)) + 
geom_point(aes(colour = K),size=2) + 
  geom_smooth(aes(group = K,color=K),method='lm',
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette,cbPalette))
```

```{r}
summary(lm(Gamma ~ 0 + K + K:Distance,data=Models.2013$ResidualsData))
```

```{r}
Selection.E <- Models.2019$Selection
Selection.E$Year <- 2019

tmp <- Models.2018$Selection
tmp$Year <- 2018
Selection.E <- rbind(Selection.E,tmp)

tmp <- Models.2017$Selection
tmp$Year <- 2017
Selection.E <- rbind(Selection.E,tmp)

tmp <- Models.2016$Selection
tmp$Year <- 2016
Selection.E <- rbind(Selection.E,tmp)

tmp <- Models.2015$Selection
tmp$Year <- 2015
Selection.E <- rbind(Selection.E,tmp)

tmp <- Models.2014$Selection
tmp$Year <- 2014
Selection.E <- rbind(Selection.E,tmp)

tmp <- Models.2013$Selection
tmp$Year <- 2013
Selection.E <- rbind(Selection.E,tmp)


BestBIC.E <- select.best.variogram(Models.2019)
BestBIC.E$Year <- 2019

tmp <- select.best.variogram(Models.2018)
tmp$Year <- 2018
BestBIC.E <- rbind(BestBIC.E,tmp)

tmp <- select.best.variogram(Models.2017)
tmp$Year <- 2017
BestBIC.E <- rbind(BestBIC.E,tmp)

tmp <- select.best.variogram(Models.2016)
tmp$Year <- 2016
BestBIC.E <- rbind(BestBIC.E,tmp)

tmp <- select.best.variogram(Models.2015)
tmp$Year <- 2015
BestBIC.E <- rbind(BestBIC.E,tmp)

tmp <- select.best.variogram(Models.2014)
tmp$Year <- 2014
BestBIC.E <- rbind(BestBIC.E,tmp)

tmp <- select.best.variogram(Models.2013)
tmp$Year <- 2013
BestBIC.E <- rbind(BestBIC.E,tmp)
```

```{r}
BestBIC.E$Year <- factor(BestBIC.E$Year)
ggplot(BestBIC.E, aes(Distance,Gamma)) + 
geom_point(aes(colour = Year),size=2) + 
   geom_smooth(aes(group = Year,color=Year),
              se=FALSE) +
 scale_colour_manual(values=c(cbPalette)) + facet_wrap(~Source)
```

```{r}
save(BestBIC.E,file='BestBIC.E.bs.Rda')
save(Selection.E,file='Selection.E.bs.Rda')
```