---
title: "Random Fields"
author: "Peter Claussen"
date: "7/2/2020"
output:
  html_document: default
  pdf_document: default
bibliography: biblio.bib
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
library(ggplot2)
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#F0E442","#CC79A7","#000000","#734f80", "#2b5a74", "#004f39", "#787221", "#003959", "#6aaf00", "#663cd3")
grey <- "#999999"
orange <- "#E69F00"
skyblue <- "#56B4E9"
bluishgreen <- "#009E73"
yellow <- "#F0E442"
blue <- "#0072B2"
vermillion <- "#D55E00"
reddishpurple <- "#CC79A7"
```

Random Fields

Abstract

# Introduction 

Suppose we have a uniformity trial, or a single season harvest. We write a model

$$
Y(\mathbf{s})=\mu(\mathbf{s})+Z(\mathbf{s})+e(\mathbf{s}) 
$$

where all variables are indexed by point
$\mathbf{s}=\left\{s_1,\dots ,s_n\right\} \in \mathbb{R}^n$ (typically,
$\mathbf{s}$ will be in $\mathbb{R}^2$ ). $Y$ is the measured yield,
usually in units such as bushels per acre. We take μ to be the expected
yield and may be estimated by an average yield over multiple growing
seasons, although for some fields we may have only the single season
data. Both $Z$ and $e$ are random variables. $Z$ is the deviation for a single
growing season from the expected yield. $e$ is a white-noise process
associated with measurement error for a sample taken at point
$\mathbf{s}$. When we have single season data we will not be able to
decompose μ and $Z$; so we may assume μ is constant 1. Or we can drop it
from the model and include it in the distribution of $Z$  and write
$Y(\mathbf{s})=\mu+Z(\mathbf{s})+e(\mathbf{s})$ We will also require
that $Z$ be continuous, while $e$ is not required to be continuous. That is,
$Z$ is a single realizaton of a random variable in $\mathbb{R}^2$, while $e$
is an arbitrary (finite) set in $\mathbb{R}$.

## Characteristics of a Random Field 
### Stationarity 
Briefly, stationarity implies that the variance of the field Z is constant over
space. When the field is non-stationary variance will be a function of
\mathbf{s}. We might2. Might. In most cases, a field of this form is
closed and bounded. Perhaps uniform vs absolute continuity state
that when Z is stationary, then Z is uniformly continuous, while Z may
be continuous, but not uniformly continuous, if non-stationary. 

### Isotropy 

We write the relationship (covariance) between yield measured
at two points $\mathbf{s},\mathbf{s}'$ as 

$$
Cov(\mathbf{s},\mathbf{s}')=E[Y(\mathbf{s})-Y(\mathbf{s}')]=Z(\mathbf{s})-Z(\mathbf{s}')+e(\mathbf{s})-e(\mathbf{s}')=Z(\mathbf{s}-\mathbf{s}')+e(\mathbf{s}-\mathbf{s}') 
$$

When $Cov(\mathbf{s},\mathbf{s}')$ depends only on the distance between
points, $\mathbf{s}-\mathbf{s}'$ a field is said to be isotropic. If
covariance depends in direction, denoted by
$|\mathbf{s}| |\mathbf{s}'|cos\theta$, then the field is said to be
anisotropic.


# References
